### PR TITLE
feat: Save artifacts from PR builds

### PR DESCRIPTION
**Pull request by clundin25**

### CODE REVIEW

**Comment by clundin25** [comment]
I believe this will reduce the toil of acquiring fresh binaries.

**Comment by clundin25** [comment]
> 

Hey Andy, thank you for bringing this up. My intention for this change is just to ease development. I found it was a frustrating experience to set up toolchains on Windows. My intent is to not replace the existing distribution mechanism, but just to add artifacts to PRs so we can quickly download artifacts and test them, without going through several manual steps.

**Review by andyrzhao — APPROVED** [review]
LGTM.

**Comment by andyrzhao** [comment]
> 

So just to confirm, it looks like the artifacts generated this way will not conflict with the signed artifacts manually uploaded to our release page correct?

**Comment by clundin25** [comment]
@andyrzhao Yes, they will just save the artifacts created by the Github Action for 90 days in the PR workflow.

Here is an example link from this PR: https://github.com/googleapis/enterprise-certificate-proxy/actions/runs/3643756747

**Pull request merged**
